# Generated by Django 3.0.2 on 2021-01-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('sender_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=13)),
                ('email', models.EmailField(max_length=50)),
                ('website', models.CharField(max_length=80)),
                ('sending_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('amount', models.CharField(max_length=10)),
                ('send_to', models.CharField(max_length=50)),
                ('reminder_count', models.IntegerField(max_length=2)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(max_length=2)),
                ('price', models.IntegerField(max_length=10)),
                ('total_amount', models.IntegerField(max_length=10)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Invoice')),
            ],
            options={
                'ordering': ['invoice_id'],
            },
        ),
    ]
