# Generated by Django 3.0.2 on 2021-01-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
